# -*- coding: utf-8 -*-
"""forth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zbX-te7dx4J0j2POOELHebA_Z6s2l6eP
"""

import pandas as pd
import numpy as np
import seaborn as sns

data = pd.read_csv("/content/diabetes.csv")

data.head()


data.columns


data.isnull().sum()

x = data.drop('Outcome', axis=1)
y = data['Outcome']

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x = scaler.fit_transform(x)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 3)
classifier

KNN = classifier.fit(x_train,y_train)
prediction = KNN.predict(x_test)
prediction
from sklearn import metrics
print(metrics.classification_report(y_test, prediction))

cm = metrics.confusion_matrix(y_test, prediction)
print(cm)

sns.heatmap(cm, annot = True)

print("accuracy:",metrics.accuracy_score(y_test,prediction))


print("error rate:",1-metrics.accuracy_score(y_test,prediction))


print("precision:",metrics.precision_score(y_test,prediction))


print("recall:",metrics.recall_score(y_test,prediction))

